package com.example.retrofittutorialapp

/*
* This class was automatically generated by copying a single JSON item from our API
* https://jsonplaceholder.typicode.com/todos and clicking new -> Kotlin Data class file from JSON
* (JsonToKotlinClass plugin installed in settings)
*
*
* */

data class Todo(
    val completed: Boolean,
    val id: Int,
    val title: String,
    val userId: Int
)